import { StyleSheet } from "react-native";
import { ColorScheme } from "@/constants/theme";

export const createStyles = (colors: ColorScheme) =>
  StyleSheet.create({
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(0,0,0,0.6)",
      zIndex: 10,
    },
    sidebar: {
      position: "absolute",
      top: 0,
      left: 0,
      bottom: 0,
      backgroundColor: colors.surface,
      zIndex: 11,
      borderRightWidth: 1,
      borderRightColor: colors.border,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingTop: 22,
      paddingBottom: 16,
    },
    headerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    logoContainer: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.text,
      letterSpacing: 0.3,
    },
    closeBtn: {
      padding: 6,
      borderRadius: 8,
      backgroundColor: colors.inputBackground,
    },
    newChatWrapper: {
      paddingHorizontal: 14,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    newChatBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.newChatBorder,
      backgroundColor: colors.newChatBg,
    },
    newChatText: {
      color: colors.primary,
      fontWeight: "600",
      fontSize: 14,
    },
    sectionLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 0.8,
      textTransform: "uppercase",
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 6,
    },
    list: {
      paddingBottom: 16,
    },
    item: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 11,
      paddingLeft: 14,
      paddingRight: 12,
      marginHorizontal: 8,
      marginVertical: 1,
      borderRadius: 10,
      overflow: "hidden",
    },
    itemActive: {
      backgroundColor: colors.activeItemBg,
    },
    activeBar: {
      position: "absolute",
      left: 0,
      top: 8,
      bottom: 8,
      width: 3,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    itemContent: {
      flex: 1,
      marginLeft: 4,
      marginRight: 8,
    },
    itemTitle: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: "500",
    },
    itemTitleActive: {
      color: colors.text,
      fontWeight: "600",
    },
    itemDate: {
      color: colors.textMuted,
      fontSize: 11,
      marginTop: 3,
      opacity: 0.7,
    },
    deleteBtn: {
      padding: 4,
      borderRadius: 6,
    },
    emptyContainer: {
      alignItems: "center",
      paddingTop: 52,
      paddingHorizontal: 24,
      gap: 10,
    },
    emptyIconWrapper: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: colors.inputBackground,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 4,
    },
    emptyTitle: {
      color: colors.textMuted,
      fontSize: 14,
      fontWeight: "600",
    },
    emptySubtitle: {
      color: colors.textMuted,
      fontSize: 12,
      textAlign: "center",
      lineHeight: 18,
      opacity: 0.6,
    },
    footer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 18,
      paddingVertical: 14,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    footerLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    footerText: {
      color: colors.textMuted,
      fontSize: 11,
      opacity: 0.7,
    },
  });
